---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name:  client
spec:
  selector:
    app: client
  ports:
    - port: 1337
      targetPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app: client
    spec:
      serviceAccountName: client
      containers:
      - name: client
        image: python
        command: ["/bin/bash"]
        args: ["-c", "while true; do echo alive; sleep 120;done"]
        ports:
          - containerPort: 1337
        imagePullPolicy: "Always"
      restartPolicy: "Always"

