---
apiVersion: v1
kind: Service
metadata:
  name: vault
  annotations:
    consul.hashicorp.com/service-ignore: "true"
spec:
  ports:
  - name: vault
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
