---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: localclient
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name:  localclient
spec:
  selector:
    app: localclient
  ports:
    - port: 1337
      targetPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localclient
  labels:
    app: localclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localclient
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app: localclient
    spec:
      serviceAccountName: localclient
      containers:
      - name: localclient
        image: python
        command: ["/bin/bash"]
        args: ["-c", "while true; do echo alive; sleep 120;done"]
        ports:
          - containerPort: 1337
        imagePullPolicy: "Always"
      restartPolicy: "Always"

