---
- name: Setup k8s worker nodes
  vars_files: vars.yml
  gather_facts: false
  hosts: all

  tasks:
  - name: Wait 300 seconds for target connection to become reachable/usable
    ansible.builtin.wait_for_connection:
    timeout: 300

  - name: Run kubeadm force reset on the node
    command: kubeadm reset -f

  - name: Reboot node to ensure all changes are applied
    command:
      cmd: python3 ../scripts/linode_reboot.py --token {{ linode_token }} --id {{ linodeid }} --reboot --ping --ip {{ ansible_host }}
    delegate_to: localhost
    connection: local

  - name: copy kubeadm join command to worker nodes
    ansible.builtin.copy:
      src: ../k8s/{{ region }}_join_command.sh
      dest: /root/{{ region }}_join_command.sh
      mode: 0755

  - name: Run kubeadm join command
    command: bash /root/{{ region }}_join_command.sh

  # pause for 30 seconds to allow the node to join the cluster
  - name: pause for 30 seconds to allow the node to join the cluster
    pause:
      seconds: 30
