---
- name: Setup consul Exported Services
  vars_files: vars.yml
  gather_facts: false
  hosts: all

  tasks:

  - name: apply consul ExportedServices
    command: kubectl apply -f /root/consul/ExportedServices.yml

